# Generated by Django 6.0.6 on 2026-06-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('sqft', models.IntegerField()),
                ('bhk', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
